# Generated by Django 5.1.1 on 2024-09-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
