# Generated by Django 5.1.1 on 2024-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_service_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="working",
            field=models.BooleanField(default=True),
        ),
    ]
